import React from "react";
import HomepageCardproduct from "../HomepageCardproduct/HomepageCardproduct";
import { NavLink } from "react-router-dom";
import { Button } from "../Button";

function Blend() {
  const info = [
    { image: "images/Kashmiri mirch.jpg", name: "Kashmiri Mirch", s1: 'Rs 10/- | 50gm | 100 gm',content:"Discover the vibrant allure of YPGold's Kashmiri Mirch, a testament to the rich culinary heritage of Kashmir. Our Kashmiri Mirch boasts a deep, ruby-red hue and a mild, fruity flavor that adds a delightful warmth to any dish. Carefully sourced and expertly blended, it lends a distinctive touch to curries, stews, and marinades. Elevate your cuisine with the enchanting flavors of YPGold's Kashmiri Mirch."},
    {image: "images/drymango.jpg",name: "Amchoor Powder",s1: 'Rs 10/- | 50gm | 100 gm',content:"Experience the tangy zest of YPGold's Amchoor Powder, a culinary delight that adds a refreshing twist to your dishes. Made from sun-dried green mangoes, our Amchoor Powder offers a burst of sourness and a subtle sweetness, enhancing the flavor profile of curries, chutneys, and marinades. Elevate your cooking with the authentic taste of YPGold's Amchoor Powder."},
    { image: "images/Chana Masala.jpg", name: "Chana Masala", s1: 'Rs 10/- | 50gm | 100 gm ',content:"Delight in the savory aroma and robust flavor of YPGold's Chana Masala, a timeless blend of spices perfected to tantalize your taste buds. Our Chana Masala combines aromatic herbs and exotic spices, creating a harmonious balance of tanginess and warmth. Whether paired with chickpeas or vegetables, it promises to elevate your dishes with authentic Indian flavors. Experience culinary excellence with YPGold's Chana Masala." },
    { image: "images/chat.jpg", name: "Chat Masala", s1: 'Rs 10/- | 50gm | 100 gm',content:"Indulge in the aromatic essence of YPGold's Chat Masala, a symphony of flavors meticulously crafted to elevate your culinary experience. Our blend of premium spices promises a burst of tangy zest and rich aroma, perfect for sprinkling over snacks or refreshing beverages. Experience the authentic taste of India with every sprinkle of YPGold's Chat Masala."},
    { image: "images/garam.jpg", name: "PRI Garam Masala", s1: 'Rs 10/- | 50gm | 100 gm',content:"Embark on a journey of flavor with PRI Garam Masala, a harmonious blend of aromatic spices crafted to perfection. Our Garam Masala infuses dishes with a symphony of warmth and depth, enhancing their taste and aroma. Made with premium ingredients, it elevates your cooking to new heights, whether sprinkled over curries, soups, or grilled delights. Experience culinary excellence with PRI Garam Masala."},
    { image: "images/jaljeera.jpg", name: "Jaljeera Masala", s1: 'Rs 10/- | 50gm | 100 gm',content:"Awaken your senses with the refreshing tang of Jaljeera Masala by YPGold. Our blend of aromatic spices and herbs creates a zesty concoction that revitalizes your taste buds. Perfect as a thirst-quencher on hot days or as a digestive aid after meals, YPGold's Jaljeera Masala offers a burst of flavor and rejuvenation in every sip. Experience the invigorating essence of Jaljeera Masala."},
    { image: "images/kitchen.jpg", name: "Kitchen King", s1: 'Rs 10/- | 50gm | 100 gm',content:"Experience culinary mastery with YPGold's Kitchen King Masala. This versatile blend of premium spices enriches your dishes with an unparalleled depth of flavor. Whether you're cooking a curry, stew, or stir-fry, YPGold's Kitchen King Masala adds a touch of royalty to every bite. Elevate your cooking and reign supreme in the kitchen with YPGold's Kitchen King Masala."},
    { image: "images/Pav Bhaji.jpg", name: "Pav Bhaji Masala",s1: 'Rs 10/- | 50gm | 100 gm',content:"Indulge in the rich and authentic flavors of Mumbai street food with YPGold's Pav Bhaji Masala. Our meticulously crafted blend of spices captures the essence of this beloved dish, offering a symphony of savory and aromatic notes. Perfectly balanced and bursting with flavor, YPGold's Pav Bhaji Masala transforms ordinary ingredients into extraordinary culinary delights. Elevate your home cooking experience with YPGold's Pav Bhaji Masala and savor the taste of Mumbai's bustling streets." },
    { image: "images/Raita Masala.jpg", name: "Raita Masala", s1: 'Rs 10/- | 50gm | 100 gm',content:"Elevate your raita to new heights with YPGold's Raita Masala. Our unique blend of spices adds a burst of flavor to your yogurt-based dishes, enhancing their taste and aroma. With just a sprinkle of YPGold's Raita Masala, you can transform a simple raita into a culinary masterpiece. Whether served as a side dish or a cooling accompaniment to spicy meals, YPGold's Raita Masala promises to delight your palate with every bite." },
    { image: "images/Sabji Masala.jpg", name: "Sabji Masala",s1: 'Rs 10/- | 50gm | 100 gm',content:"Infuse your vegetables with a burst of flavor using YPGold's Sabji Masala. Our expertly crafted blend of spices brings out the natural goodness of your veggies, elevating them to gourmet status. With just a sprinkle of YPGold's Sabji Masala, you can turn ordinary stir-fries and curries into extraordinary culinary creations. Add depth and complexity to your dishes with YPGold's Sabji Masala and savor the rich flavors of Indian cuisine."},
    { image: "images/sambar.jpg", name: "Sambar Masala", s1: 'Rs 10/- | 50gm | 100 gm',content:"Transport your taste buds to the vibrant streets of South India with YPGold's Sambar Masala. Our authentic blend of spices captures the essence of traditional sambar, infusing your dishes with a symphony of flavors. With YPGold's Sambar Masala, you can recreate the rich and aromatic taste of this iconic dish right in your own kitchen. Whether paired with rice or enjoyed as a hearty soup, YPGold's Sambar Masala promises to satisfy your cravings for authentic South Indian cuisine." },
    { image: "images/saunth.jpg", name: "Saunth Powder", s1: 'Rs 10/- | 50gm | 100 gm',content:"Savor the exotic essence of Saunth Powder by YPGold. Our meticulously crafted blend of spices captures the essence of traditional Indian cuisine, adding a delightful depth of flavor to your dishes. With a hint of sweetness and a touch of warmth, YPGold's Saunth Powder elevates your culinary creations to new heights. Whether used in curries, marinades, or snacks, YPGold's Saunth Powder promises to tantalize your taste buds with its irresistible aroma and taste." },
    { image: "images/Meat Masala.jpg", name: "SPL. Meat Masala", s1: 'Rs 10/- | 50gm | 100 gm',content:"Indulge in the rich and robust flavors of YPGold's SPL. Meat Masala. Carefully crafted with a blend of premium spices, our SPL. Meat Masala enhances the taste and aroma of your meat dishes, turning every meal into a culinary delight. Whether you're grilling, roasting, or stewing, YPGold's SPL. Meat Masala adds a burst of flavor that will tantalize your taste buds and leave you craving for more. Elevate your meat dishes to gourmet status with YPGold's SPL. Meat Masala." },
    { image: "images/Shahi paneer.jpg", name: "Shahi Paneer Masala", s1: 'Rs 10/- | 50gm | 100 gm',content:"Experience the royal flavors of Shahi Paneer Masala by YPGold. Crafted with a blend of premium spices fit for royalty, our Shahi Paneer Masala elevates your homemade paneer dishes to regal heights. With its rich and aromatic profile, YPGold's Shahi Paneer Masala brings out the true essence of this classic North Indian delicacy. Treat yourself to a taste of luxury and indulge in the exquisite flavors of Shahi Paneer Masala by YPGold."},
    { image: "images/jeera.jpg", name: "Jeera Powder", s1: 'Rs 10/- | 50gm | 100 gm',content:"Enhance your dishes with the earthy aroma and distinctive flavor of YPGold's Jeera Powder. Carefully ground from premium cumin seeds, our Jeera Powder adds depth and richness to your culinary creations. Whether sprinkled over rice, incorporated into curries, or used as a seasoning for snacks, YPGold's Jeera Powder brings a touch of warmth and complexity to every dish. Elevate your cooking with the authentic taste of Jeera Powder by YPGold." },
    { image: "images/Pudhina.jpg", name: "Pudina Powder", s1: 'Rs 10/- | 50 gm',content:"Refresh your palate with the cool and invigorating flavor of YPGold's Pudina Powder. Made from freshly ground mint leaves, our Pudina Powder adds a burst of freshness to your dishes. Whether sprinkled over salads, mixed into yogurt dips, or infused into beverages, YPGold's Pudina Powder brings a delightful minty zing to every bite. Elevate your cooking with the refreshing taste of Pudina Powder by YPGold and experience a burst of flavor in every dish." },
    { image: "images/Pani Puri.jpg", name: "Pani Puri Masala",s1: 'Rs 10/- | 50 gm',content:"Experience the authentic taste of street food with YPGold's Pani Puri Masala. Crafted with a blend of tangy spices and aromatic herbs, our Pani Puri Masala brings the flavors of the bustling streets to your home. Just a sprinkle of YPGold's Pani Puri Masala is all you need to recreate the classic pani puri experience. Whether you're hosting a party or craving a snack, YPGold's Pani Puri Masala promises to tantalize your taste buds and transport you to the vibrant streets of India."  },
    { image: "images/blackpeper.jpg", name: "Black Pepper Powder", s1: 'Rs 10/- 50gm | 100 gm',content:"Add a touch of boldness to your dishes with YPGold's Black Pepper Powder. Sourced from the finest peppercorns, our Black Pepper Powder delivers a robust flavor and subtle heat that enhances any recipe. Whether sprinkled over salads, soups, or grilled dishes, YPGold's Black Pepper Powder elevates the taste of your culinary creations. With its rich aroma and distinct flavor profile, YPGold's Black Pepper Powder is a must-have in every kitchen for adding depth and complexity to your cooking."  },
    { image: "images/sauf.jpg", name: "Saunf Powder", s1: '50 gm',content:"Elevate your culinary creations with the aromatic essence of YPGold's Saunf Powder. Carefully ground from premium fennel seeds, our Saunf Powder adds a delightful sweetness and subtle licorice flavor to your dishes. Whether used in curries, desserts, or beverages, YPGold's Saunf Powder enhances the taste and aroma of your recipes. With its versatile nature and rich fragrance, YPGold's Saunf Powder is the perfect addition to your spice collection, promising to delight your taste buds with every sprinkle." },
    { image: "images/anardana.jpg", name: "Anardana Powder", s1: '50 gm' ,content:"Experience the tangy burst of flavor with YPGold's Anardana Powder. Sourced from premium pomegranate seeds, our Anardana Powder adds a delightful tartness and depth to your dishes. Whether sprinkled over salads, incorporated into marinades, or used as a seasoning for meats and vegetables, YPGold's Anardana Powder elevates the taste of your culinary creations. With its unique flavor profile and versatile usage, YPGold's Anardana Powder is a must-have ingredient for adding a refreshing twist to your recipes." },
    { image: "images/Matar_paneer.jpg", name: "Matar Paneer Masala", s1: 'Rs 10/- 50gm | 100 gm',content:"Indulge in the rich and creamy flavors of YPGold's Matar Paneer Masala. Crafted with a blend of aromatic spices and herbs, our Matar Paneer Masala transforms simple ingredients into a delectable dish bursting with flavor. Whether you're cooking for a family dinner or entertaining guests, YPGold's Matar Paneer Masala adds a touch of elegance and authenticity to your meal. Elevate your culinary creations with the irresistible taste of Matar Paneer Masala by YPGold."  },
    { image: "images/soya_chaap.jpeg", name: "Soya Chaap Masala", s1: 'Rs 10/- 50gm | 100 gm',content:"Elevate your vegetarian cuisine with the bold and savory flavors of YPGold's Soya Chaap Masala. Crafted with a blend of aromatic spices and herbs, our Soya Chaap Masala enhances the taste and texture of your favorite soy-based dishes. Whether grilled, fried, or simmered in a rich curry, YPGold's Soya Chaap Masala adds depth and complexity, turning every bite into a culinary delight. Experience the indulgent flavors of Soya Chaap Masala by YPGold and elevate your vegetarian meals to new heights."  },
  ];

  return (
    <>
     <div className="mx-auto grid w-full items-center  ">
        {info.map((info, i) => (
          <div key={i} className={`w-full h-[550px] max-[450px]:h-[700px] ${i % 2 === 0 ? 'bg-[#F0F0F0] ' : 'bg-[white]'}  `}>
            <div key={i} className={` relative w-full flex max-[450px]:flex max-[450px]:flex-col-reverse max-[450px]: justify-center gap-12 ${i % 2 === 0 ? 'flex-row-reverse' : 'flex-row'}`}>
              <div className="justify-start w-1/3 mt-[6.5rem] max-[450px]:w-full max-[450px]:mt-[-2rem] max-[450px]:py-[-2rem]">
                <div className="text-3xl"><h1>{info.name}</h1></div>
                <div className="mt-3 "><p>{info.content}</p></div>
                <div className="flex max-[450px]:flex-col max-[450px]:mt-0 mt-3">
                  <div className="mt-2.5 flex-col  space-x-2 min-[320px]:w-70">
                      <h3 className="text-bold text-black-900">Available Sizes</h3>
                      <h4 className="text-bold">{info.s1}</h4>
                  </div>

                  <div className="dropdown dropdown-hover py-2 pr-4 pl-3 relative max-[450px]:mt-2">
                    <Button class="flex items-center text-[#0097CC] rounded-full border-solid border-2 border-[#0097CC] hover:bg-[#0097CC] hover:text-white-A700 p-2 w-auto">
                      Online order <img src="images/img_arrow_down.svg" alt="" class="ml-2 " />
                    </Button>

                    <ul tabIndex={0} className="dropdown-content z-[1] menu shadow h-[8rem] max-[450px]:w-[25rem] w-[32rem] bg-white-A700 grid grid-cols-3 gap-10 p-4 ">
                      <li className="w-28 h-[6rem] border border-solid border-gray-500 hover:bg-[#0097CC]"><NavLink to="https://www.flipkart.com/search?q=ypgold%20masala&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"><img className="" src="images/flipkartlogo.png" alt="" /></NavLink></li>
                      <li className="w-28 h-[6rem] border border-solid border-gray-500 hover:bg-[#0097CC]"><NavLink to={"https://blinkit.com/"}><img className="" src="images/blinkit.svg" alt="" /></NavLink></li>
                      <li className="w-28 h-[6rem] border border-solid border-gray-500 hover:bg-[#0097CC]"><NavLink to={"https://www.meesho.com/"}><img className="w-60 h-[4rem]" src="https://upload.wikimedia.org/wikipedia/commons/3/33/Meesho_logo.png" alt="" /></NavLink></li>
                    </ul>

                  </div>

                </div>
              </div>
              <div className="mt-[6.5rem] max-[450px]:mt-3"><img className="h-72 w-72 mix-blend-multiply" src={info.image} alt="" />
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}

export default Blend;
